# Generated by Django 3.1.2 on 2021-04-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210409_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.CharField(default='', max_length=100, verbose_name='头像'),
        ),
    ]
